defmodule Test.Repo.Migrations.All do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:trades, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :state, :text
    end

    create table(:scheduled_trades, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :plan_id, :uuid
      add :trade_id, :uuid
    end

    create table(:plans, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:scheduled_trades) do
      modify :plan_id,
             references(:plans,
               column: :id,
               name: "scheduled_trades_plan_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :trade_id,
             references(:trades,
               column: :id,
               name: "scheduled_trades_trade_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:scheduled_trades, "scheduled_trades_plan_id_fkey")

    drop constraint(:scheduled_trades, "scheduled_trades_trade_id_fkey")

    alter table(:scheduled_trades) do
      modify :trade_id, :uuid
      modify :plan_id, :uuid
    end

    drop table(:plans)

    drop table(:scheduled_trades)

    drop table(:trades)
  end
end